/*
 * This source file was generated by the Gradle 'init' task
 */
package org.core;

import java.util.Scanner;

import org.core.models.Driver;
import org.core.models.Location;
import org.core.models.Ride;
import org.core.services.CalculateService;
import org.core.services.RegisterService;
import org.core.services.RideMatchingService;

public class App {

    public static void main(String[] args) {

        RideMatchingService rideService = new RideMatchingService();
        try (Scanner sc = new Scanner(System.in)) {
            while (true) {
                System.out.println("\n===== Ride Matching System =====");
                System.out.println("1. Register Driver");
                System.out.println("2. Request Ride");
                System.out.println("3. Complete Ride");
                System.out.println("4. View Available Drivers");
                System.out.println("5. Exit");

                int choice = Utility.readValidOption(sc, "Choose option: ");

                switch (choice) {

                    case 1 -> {
                        String driverId = Utility.readValidString(sc, "Driver ID");

                        String driverName = Utility.readValidString(sc, "Driver Name");

                        String xStr = Utility.readCoordinate(sc, "Location X");

                        String yStr = Utility.readCoordinate(sc, "Location Y");

                        RegisterService.registerDriver(driverId,
                                new Driver(driverId, driverName, new Location(xStr, yStr)));

                        System.out.println("Driver registered/updated successfully.");
                    }

                    case 2 -> {
                        String xStr = Utility.readCoordinate(sc, "Pickup location X");

                        String yStr = Utility.readCoordinate(sc, "Pickup location Y");

                        try {
                            Ride ride = rideService.requestRide(new Location(xStr, yStr),
                                    RideMatchingService.DEFAULT_NUMBER_OF_DRIVERS);
                            System.out.println("Ride created!");
                            System.out.println("Ride ID: " + ride.getId());
                            System.out.println("Driver name: " + ride.getDriver().getName());
                            System.out.println("Driver ID: " + ride.getDriver().getId());
                        } catch (IllegalArgumentException | IllegalStateException e) {
                            System.out.println("[Error] " + e.getMessage() + ". Going back to main menu.");
                        }
                    }

                    case 3 -> {
                        String rideId = Utility.readValidString(sc, "Ride ID");

                        try {
                            rideService.completeRide(rideId);
                            System.out.println("Ride completed.");
                        } catch (IllegalArgumentException | IllegalStateException e) {
                            System.out.println("[Error] " + e.getMessage() + ". Going back to main menu.");
                        }
                    }

                    case 4 -> {
                        String xStr = Utility.readCoordinate(sc, "Location X");

                        String yStr = Utility.readCoordinate(sc, "Location Y");

                        int limit = Utility.readPositiveNumber(sc, "Find X nearest drivers");

                        var drivers = CalculateService.getNearestAvailableDrivers(
                                RegisterService.getAvailableDrivers(),
                                new Location(xStr, yStr),
                                limit);
                        if (!drivers.isEmpty()) {
                            System.out.println("Nearest available drivers:");
                            for (Driver driver : drivers) {
                                System.out.println("- " + driver.getId()
                                        + " | " + driver.getName()
                                        + " | (" + driver.getLocation().x() + "," + driver.getLocation().y() + ")");
                            }
                        } else {
                            System.out.println("No available driver, please try again later.");
                        }

                    }

                    case 5 -> {
                        System.out.println("Exiting...");
                        return;
                    }

                    default -> System.out.println("Invalid option");
                }
            }
        } catch (Exception e) {
            System.err.println("An unexpected error occurred:\n" + e.getMessage());
        }
    }
}
